export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const ASSOCIATE_REPOSITORY = 'ASSOCIATE_REPOSITORY';
export const SPECIALIZATION_REPOSITORY = 'SPECIALIZATION_REPOSITORY';
export const ASSOCIATE_SPECIALIZATION_REPOSITORY =
  'ASSOCIATE_SPECIALIZATION_REPOSITORY';

export const ASSOCIATE_SERVICE = 'ASSOCIATE_SERVICE';
export const SPECIALIZATION_SERVICE = 'SPECIALIZATION_SERVICE';
export const ASSOCIATE_SPECIALIZATION_SERVICE =
  'ASSOCIATE_SPECIALIZATION_SERVICE';
